### ISSUE TITLE
I 've made a unity unsafe / jobs / NativeArray version of the bindings

### ISSUE THREAD

**Issue by Neovariance** [Auburn/FastNoise2Bindings#3]
Before I do a pull request, can we agree on how to organize the files ? 

To be user friendly, there should be a UnityProject /Asset Folder, a test scene with simple test class, and a UnityProject /Packages/manifest.json with the job/burst/mathematics dependencies

Option 1 : Another Repo dedicated to Unity that I maintain myself with a git submodule to fetch your csharp folder into Assets/scripts, so any future update you may make to Fastnoise2.cs gets automatically included, and I use a partial Class with my additions.

Option 2 : Same but you create the repo

Option 3 :  I do a pull request with a FastNoise2Bindings/UnityProject folder to put at the root level, with a NativeFastNoise2.cs completely independent from Fastnoise2.cs (so there is some code duplication)

Or any other idea you have.

**Comment by Auburn** [comment]
Cool! I'd prefer option 3
