### ISSUE TITLE
DLL in repository is probably missing fnDeleteNodeRef / Disposable pattern

### ISSUE THREAD

**Issue by BlakkM9** [Auburn/FastNoise2Bindings#5]
I've re-written some of the code now and when I converted the FastNoise2 class to use the disposable pattern, whenever fnDeleteNodeRef was called it threw a EntryPointNotFoundException.

I think it didn't happen in the bitmap example because the destructor (or rather finalizer) is not called in a non-deterministic way. I'm not 100% sure about that but after I've replaced the dll with its newest version that error was gone.

Also: is there maybe even a specific reason why you've decided to not go for the Disposable pattern yourself?

It is probably not that important because people can easily replace the dll themselfes but I figured it might be worth mentioning.

**Comment by Auburn** [comment]
It seems odd that no one else has come across the issue of `fnDeleteNodeRef` being missing in the DLL, does switching to the latest DLL fix the that?

I'm not that familiar with C# to know about the disposable pattern, what benefits would it provide in this use case?

**Comment by BlakkM9** [comment]
Ok, I've confirmed my suspection now.

Steps of reproduction:

1. Close repository
2. Open FastNoise2BitmapGenerator.csproj with Visual Studio (2022, Version 17.3.5)
3. Remove Finalizer and place `fnDeleteNodeRef(IntPtr)` in a seperate member function of FastNoise2.cs
4. Call the newly created method after creating a new instance of `FastNoise`

Relevant code:
FastNoise2.cs
```
//~FastNoise()
//{
//    fnDeleteNodeRef(mNodeHandle);
//}


public void DeleteNodeRef()
{
    fnDeleteNodeRef(mNodeHandle);
}
```

BitmapGenerator.cs
```
static void Main(string args[])
{
    FastNoise cellular = new FastNoise("CellularDistance");
    cellular.DeleteNodeRef();
}
```

> System.EntryPointNotFoundException: 'Unable to find an entry point named 'fnDeleteNodeRef' in DLL 'FastNoise'.'

is thrown.

5.  Delete bin and obj folderes
6.  Replace the old DLL with the newest one (Downloaded from Release: FastNoise2-v0.9.6-alpha-Win64-MSVC)

Now the exception is no longer thrown.

For why no one else seemed to get that error: Maybe most people just go straight to using the newest DLL or don't bother creating an issue and go on without using these bindings, but it really is strange. Also maybe the error will not appear if the NodeRef is deleted in the finalizer (but surely it is not intended like this and might cause memory leaks)

My C/C++ knowledge is limited but I guess `fnDeleteNodeRef(IntPtr)` is just reseting a shared_ptr internally or something like that, right?

Also my offer still exists. It really would be nice if there would be an official NuGet package for the bindings that automatically include the newest DLL (if that is even possible).

**Comment by Auburn** [comment]
Thanks for the sleuthing! Not sure why the old DLL is missing the function, at least it's an easy fix! 

Can you PR the finalise change? I'm also happy to have it in a Nuget package, just wondering how that works given that currently FastNoise2 only supports x86. Does Nuget even allow downloading random binaries?

**Comment by BlakkM9** [comment]
I've mostly changed the structure of your code, moved everything to seperate files etc so not sure if you're happy with that but you can check the PR then :)

I'm busy for the next few days so that could probably take about a week until PR, especially because I have never done NuGet  packages so far so I'll have to do some reseach aswell.

At the very least you can ship DLLs with NuGet packages but I'll check that once I'm available again.

If any questions in that regard occur, do you prefer communication via Discord or rather keep it in this issue thread?

**Comment by Auburn** [comment]
We can chat on discord, I've resolved this issue by pushing the new FastNoise.dll into the repo. Looking at the old DLL with Dependency Walker `fnDeleteNodeRef` is indeed missing.
